FROM apache/airflow:2.8.1

USER root
RUN apt-get update && apt-get install -y git && apt-get clean

USER airflow

# Instalar dependencias Python
RUN pip install --no-cache-dir \
    dbt-duckdb>=1.7.0 \
    pandas>=2.0.0 \
    requests>=2.31.0 \
    pyarrow>=14.0.0 \
    duckdb>=0.9.0
