name: 'ordenes_analytics'
version: '1.0.0'
config-version: 2

profile: 'ordenes_analytics'

model-paths: ["models"]
macro-paths: ["macros"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  ordenes_analytics:
    bronze:
      +materialized: table
      +tags: ['bronze', 'raw']
    silver:
      +materialized: table
      +tags: ['silver', 'cleaned']
    gold:
      +materialized: table
      +tags: ['gold', 'analytics']

vars:
  data_path: '/opt/airflow/data'