ordenes_analytics:
  outputs:
    dev:
      type: duckdb
      path: /opt/airflow/project/ordenes_analytics/ordenes.duckdb
      threads: 4
    local:
      type: duckdb
      path: ./ordenes.duckdb
      threads: 4
  target: dev